### PR TITLE
Add checkstyle plugin and format code

### PR DESCRIPTION
**Pull request by sakama**
* Upgrade Gradle version because checkstyle plugin doesn't work Gradle 2.2.1.
    * [Allowing gradle to use checkstyle 6.8+ by ethankhall · Pull Request #491 · gradle/gradle](https://github.com/gradle/gradle/pull/491)
* Add checkstyle plugin
* Code formatted

### CODE REVIEW

**Comment by hakobera** [comment]
@sakama Why do you use checkstyle rules based on [presto](https://github.com/prestodb/presto/blob/master/src/checkstyle/checks.xml)?

It's default rules for embulk Java plugins?

**Comment by sakama** [comment]
@hakobera

> It's default rules for embulk Java plugins?

Unfortunately, no rules were documented at [embulk.org](http://www.embulk.org/).
Additionally, both of [embulk-core](https://github.com/embulk/embulk/tree/master/embulk-core) and [embulk-standards](https://github.com/embulk/embulk/tree/master/embulk-standards) are not formatted with this for now.
But current `embulk new` commands generates template with checkstyle plugin and this XML.

```
$ embulk new java-input test
...
Creating embulk-input-test/
  Creating embulk-input-test/README.md
  Creating embulk-input-test/LICENSE.txt
  Creating embulk-input-test/.gitignore
  Creating embulk-input-test/gradle/wrapper/gradle-wrapper.jar
  Creating embulk-input-test/gradle/wrapper/gradle-wrapper.properties
  Creating embulk-input-test/gradlew.bat
  Creating embulk-input-test/gradlew
  Creating embulk-input-test/config/checkstyle/checkstyle.xml
  Creating embulk-input-test/config/checkstyle/default.xml
  Creating embulk-input-test/build.gradle
  Creating embulk-input-test/lib/embulk/input/test.rb
  Creating embulk-input-test/src/main/java/org/embulk/input/test/TestInputPlugin.java
  Creating embulk-input-test/src/test/java/org/embulk/input/test/TestTestInputPlugin.java
```

As you saying, there're many opinions which format is good.

**Comment by hakobera** [comment]
> But current embulk new commands generates template with checkstyle plugin and this XML.

@sakama I see, and I confirmed it in my local machine. So this checkstyle rule is almost official rule, so I'm glad to apply it 👍

**Comment by hakobera** [comment]
This PR is only include code format and add checkstyle. So I'm not release new version to rubygem.org now.

**Comment by sakama** [comment]
Thanks 👍

**Pull request merged**
