### PR TITLE
Add limit and skip option

### PR DESCRIPTION
**Pull request by sakama**
I added `limit` and `skip` option for plugin.

Plugin will throw ConfigException when both of `skip` and `incremental_field` are set.
This behavior is same with `sort` option.

### CODE REVIEW

**Comment by sakama** [comment]
CI failure with (Oracle|Open) JDK7 will be fixed at #30

**Comment by bcipolli** [comment]
Thank you so much! This looks very good to me. I think it would be helpful to have two additional tests:

* Test for `limit(1)`
* Test for `limit(1)` with incremental load.

I see that there's a good framework for writing such tests. Each of these would guarantee that `limit` works, and that it works with incremental load.

**Comment by sakama** [comment]
Thanks for take a look!
I added additional unit test cases that you mentioned.

**Comment by bcipolli** [comment]
Looks good, thank you! When you merge this, I will try using for our company's ETL. Thank you!

**Comment by sakama** [comment]
@hakobera I don't have permission to merge.
Could you take a look #30 and this?

**Comment by mjalkio** [comment]
Tested the limit feature, seems to be working 👍

**Comment by kamatama41** [comment]
@sakama @bcipolli @mjalkio 
Sorry for late response. It looks good to me 👍 
I'll release it soon.

**Pull request merged**
